# Generated by Django 5.1.4 on 2025-01-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "natiolanity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("US", "United States"),
                            ("CA", "Canada"),
                            ("MX", "Mexico"),
                            ("ES", "Spain"),
                            ("FR", "France"),
                            ("IT", "Italy"),
                            ("DE", "Germany"),
                            ("GB", "United Kingdom"),
                            ("AU", "Australia"),
                            ("JP", "Japan"),
                            ("CN", "China"),
                            ("BR", "Brazil"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
