# Generated by Django 5.1.4 on 2025-01-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="nationality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("US", "United States"),
                    ("CA", "Canada"),
                    ("MX", "Mexico"),
                    ("ES", "Spain"),
                    ("FR", "France"),
                    ("IT", "Italy"),
                    ("DE", "Germany"),
                    ("GB", "United Kingdom"),
                    ("AU", "Australia"),
                    ("JP", "Japan"),
                    ("CN", "China"),
                    ("BR", "Brazil"),
                    ("LB", "Libanon"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
