# Generated by Django 5.1.4 on 2025-01-02 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("actors", "0001_initial"),
        ("genres", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("release_date", models.DateField()),
                ("resume", models.TextField()),
                (
                    "actors",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="actors.actor"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movies",
                        to="genres.genre",
                    ),
                ),
            ],
        ),
    ]
